// modules/spd2010_display/qstrdefs.h
Q(spd2010_display)
Q(LCD_WIDTH)
Q(LCD_HEIGHT)
Q(LCD_COLOR_BITS)
Q(LCD_Backlight_PIN)
Q(Backlight_MAX)
Q(SPD2010_Reset)
Q(QSPI_Init)
Q(SPD2010_Init)
Q(LCD_addWindow)
Q(Backlight_Init)
Q(Set_Backlight)
Q(LCD_Init)